name: ACCP macOS CI

# Workflow syntax.
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
on:
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

env:
  PACKAGE_NAME: ACCP

jobs:
  # JDK 8 job.
  macOS8:
    name: JDK8
    runs-on: macos-latest-large
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install dependencies from brew
      run: |
        env HOMEBREW_NO_AUTO_UPDATE=1 brew install lcov golang
    - name: Setup pip
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
    - name: Install gcovr
      run: |
        pip install gcovr

    # Set up Corretto 8. The JDK version should be least 10 for a regular ACCP build,
    # but JAVA_HOME will be overwritten with subsequent versions we set up, so we save
    # the path here beforehand.
    - name: Set up corretto 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'corretto'
    - name: Get JAVA_HOME variable for correto 8
      run: |
        echo "JAVA8_HOME=${{ env.JAVA_HOME }}" >> $GITHUB_ENV
    # Set up Corretto 11.
    - name: Set up corretto 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'corretto'

    # Test on Corretto 8. Built with JDK11, but tested with JDK8.
    - name: Build and run tests for ${{ env.PACKAGE_NAME }} in corretto 8
      env:
        TEST_JAVA_HOME: ${{ env.JAVA8_HOME }}
      run: |
        ./tests/ci/run_accp_basic_tests.sh --lcov-ignore inconsistent
        ./tests/ci/run_accp_test_integration.sh
  # JDK 11 job.
  macOS11:
    name: JDK11
    runs-on: macos-latest-large
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install dependencies from brew
      run: |
        env HOMEBREW_NO_AUTO_UPDATE=1 brew install lcov golang
    - name: Setup pip
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
    - name: Install gcovr
      run: |
        pip install gcovr

    # Set up Corretto 11.
    - name: Set up corretto 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'corretto'

    # Test on Corretto 11 targeting JDK 8.
    - name: Build and run tests for ${{ env.PACKAGE_NAME }} in corretto 11
      env:
        TEST_JAVA_HOME: ${{ env.JAVA_HOME }}
      run: |
        ./tests/ci/run_accp_basic_tests.sh --lcov-ignore inconsistent
        ./tests/ci/run_accp_test_integration.sh
  # JDK 17 job.
  macOS17:
    name: JDK17
    runs-on: macos-latest-large
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install dependencies from brew
      run: |
        env HOMEBREW_NO_AUTO_UPDATE=1 brew install lcov golang
    - name: Setup pip
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
    - name: Install gcovr
      run: |
        pip install gcovr
    # Set up Corretto 17.
    - name: Set up corretto 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
    # Test on Corretto 17 targeting JDK 8.
    - name: Build and run tests for ${{ env.PACKAGE_NAME }} in corretto 17
      env:
        TEST_JAVA_HOME: ${{ env.JAVA_HOME }}
      run: |
        ./tests/ci/run_accp_basic_tests.sh --lcov-ignore inconsistent
        ./tests/ci/run_accp_test_integration.sh
  # JDK 8 Arm64 job.
  macOS8Arm:
    name: JDK8ARM
    runs-on: macos-latest-xlarge
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install dependencies from brew
      run: |
        env HOMEBREW_NO_AUTO_UPDATE=1 brew install lcov golang
    - name: Setup pip
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'
    - name: Install gcovr
      run: |
        pip install gcovr

    # Set up Corretto 8. The JDK version should be least 10 for a regular ACCP build,
    # but JAVA_HOME will be overwritten with subsequent versions we set up, so we save
    # the path here beforehand.
    - name: Set up corretto 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'corretto'
    - name: Get JAVA_HOME variable for correto 8
      run: |
        echo "JAVA8_HOME=${{ env.JAVA_HOME }}" >> $GITHUB_ENV
    # Set up Corretto 11.
    - name: Set up corretto 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'corretto'

    # Test on Corretto 8. Built with JDK11, but tested with JDK8.
    - name: Build and run tests for ${{ env.PACKAGE_NAME }} in corretto 8
      env:
        TEST_JAVA_HOME: ${{ env.JAVA8_HOME }}
      run: |
        ./tests/ci/run_accp_basic_tests.sh --lcov-ignore inconsistent
        ./tests/ci/run_accp_test_integration.sh
  # JDK 11 Arm64 job.
  macOS11Arm:
    name: JDK11ARM
    runs-on: macos-latest-xlarge
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install dependencies from brew
      run: |
        env HOMEBREW_NO_AUTO_UPDATE=1 brew install lcov golang
    - name: Setup pip
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'
    - name: Install gcovr
      run: |
        pip install gcovr

    # Set up Corretto 11.
    - name: Set up corretto 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'corretto'

    # Test on Corretto 11 targeting JDK 8.
    - name: Build and run tests for ${{ env.PACKAGE_NAME }} in corretto 11
      env:
        TEST_JAVA_HOME: ${{ env.JAVA_HOME }}
      run: |
        ./tests/ci/run_accp_basic_tests.sh --lcov-ignore inconsistent
        ./tests/ci/run_accp_test_integration.sh
  # JDK 17 Arm64 job.
  macOS17Arm:
    name: JDK17ARM
    runs-on: macos-latest-xlarge
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install lcov dependencies from brew
      run: |
        env HOMEBREW_NO_AUTO_UPDATE=1 brew install lcov golang
    - name: Setup pip
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'
    - name: Install gcovr
      run: |
        pip install gcovr
    # Set up Corretto 17.
    - name: Set up corretto 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
    # Test on Corretto 17 build targeting JDK 8.
    - name: Build and run tests for ${{ env.PACKAGE_NAME }} in corretto 17
      env:
        TEST_JAVA_HOME: ${{ env.JAVA_HOME }}
      run: |
        ./tests/ci/run_accp_basic_tests.sh --lcov-ignore inconsistent
        ./tests/ci/run_accp_test_integration.sh
  macOS17ArmTarget17:
    name: JDK17ARM-TARGET-JDK17
    runs-on: macos-latest-xlarge
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install lcov dependencies from brew
      run: |
        env HOMEBREW_NO_AUTO_UPDATE=1 brew install lcov golang
    - name: Setup pip
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'
    - name: Install gcovr
      run: |
        pip install gcovr
    # Set up Corretto 17.
    - name: Set up corretto 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
    # Test on Corretto 17 build targeting JDK 17.
    - name: Build and run tests for ${{ env.PACKAGE_NAME }} in corretto 17 targeting JDK 17 to include the jdk17plus folder
      env:
        TEST_JAVA_HOME: ${{ env.JAVA_HOME }}
      run: |
        ./tests/ci/run_accp_basic_tests.sh --lcov-ignore inconsistent --target-jdk-version 17
        ./tests/ci/run_accp_test_integration.sh
  macOS21ArmTarget21:
    name: JDK21ARM-TARGET-JDK21
    runs-on: macos-latest-xlarge
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install lcov dependencies from brew
      run: |
        env HOMEBREW_NO_AUTO_UPDATE=1 brew install lcov golang
    - name: Setup pip
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'
    - name: Install gcovr
      run: |
        pip install gcovr
    # Set up Corretto 21.
    - name: Set up corretto 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'corretto'
    # Test on Corretto 21 build targeting JDK 21 .
    - name: Build and run tests for ${{ env.PACKAGE_NAME }} in corretto 21 targeting JDK 21 to include the jdk17plus folder
      env:
        TEST_JAVA_HOME: ${{ env.JAVA_HOME }}
      run: |
        ./tests/ci/run_accp_basic_tests.sh --lcov-ignore inconsistent --target-jdk-version 21
        ./tests/ci/run_accp_test_integration.sh
