name: ACCP macOS CI FIPS

# Workflow syntax.
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
on:
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

env:
  PACKAGE_NAME: ACCP-FIPS

jobs:
  # Job to run FIPS version of ACCP tests on MacOS.
  macOS:
    runs-on: macos-11 # latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install lcov
      run: |
        env HOMEBREW_NO_AUTO_UPDATE=1 brew install lcov
    - name: Setup pip
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
    - name: Install gcovr
      run: |
        pip install gcovr

    # Set up Corretto 8. The JDK version should be least 10 for a regular ACCP build,
    # but JAVA_HOME will be overwritten with subsequent versions we set up, so we save
    # the path here beforehand.
    - name: Set up corretto 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'corretto'
    - name: Get JAVA_HOME variable for correto 8
      run: |
        echo "JAVA8_HOME=${{ env.JAVA_HOME }}" >> $GITHUB_ENV
    # Set up Corretto 11.
    - name: Set up corretto 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'corretto'

    # Test on Corretto 8. Built with JDK11, but tested with JDK8.
    - name: Build and run tests for ${{ env.PACKAGE_NAME }} in corretto 8
      env:
        TEST_JAVA_HOME: ${{ env.JAVA8_HOME }}
      run: |
        ./tests/ci/run_accp_basic_tests.sh --fips
        ./tests/ci/run_accp_test_integration.sh --fips
     # Test on Corretto 11.
    - name: Build and run tests for ${{ env.PACKAGE_NAME }} in corretto 11
      env:
        TEST_JAVA_HOME: ${{ env.JAVA_HOME }}
      run: |
        ./tests/ci/run_accp_basic_tests.sh --fips
        ./tests/ci/run_accp_test_integration.sh --fips

    # Test on Corretto 17.
    - name: Set up corretto 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
    - name: Build and run tests for ${{ env.PACKAGE_NAME }} in corretto 17
      env:
        TEST_JAVA_HOME: ${{ env.JAVA_HOME }}
      run: |
        ./tests/ci/run_accp_basic_tests.sh --fips
        ./tests/ci/run_accp_test_integration.sh --fips
